version: '3.4'

services:
  invoicemanagementsystem.webapi:
    image: ${DOCKER_REGISTRY-}invoicemanagementsystemwebapi
    build:
      context: .
      dockerfile: src/InvoiceManagementSystem.WebAPI/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server"